In [3]:
import numpy as np

In [43]:
my_list = [10, 20, 30,40]

arr = np.array(my_list)

print(arr.dtype)
print(arr.shape)

arr = np.array(my_list)

int64
(4,)


In [9]:
arr.shape

(4,)

In [10]:
list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
twod_array = np.array(list_of_lists)

twod_array.shape

(3, 3)

In [11]:
my_list = [10, 20, 30]

arr = np.array(my_list)

print(arr.dtype)
print(arr.shape)

int64
(3,)


In [13]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(0, 10, 2, dtype='int32')

array([0, 2, 4, 6, 8], dtype=int32)

In [30]:
np.arange(0, 10, 3, dtype='int32', like=twod_array)

array([0, 3, 6, 9], dtype=int32)

In [69]:
arr = np.arange(0, 10, 1)  # Create the array
arr_str = arr.astype(str)   # Convert to string type
print(arr_str)

['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']


In [31]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
# divide into 5 interval from 0 to 10
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
np.linspace(0, 10, num=5, endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [46]:
np.linspace(0, 10, num=5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [53]:
np.linspace(0, 10, num=5, endpoint=True, retstep=True)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))

In [58]:
# random number (uniform distribution) array of shape (1 , 2)
np.random.rand(1,2)

array([[0.81753751, 0.26539535]])

In [59]:
np.random.rand(1,2,3)

array([[[0.58913107, 0.30745572, 0.40147169],
        [0.36321974, 0.77072728, 0.52937856]]])

In [60]:
# random number (standard normal distribution) array of shape (2, 3)
print (np.random.randn(2, 3))


[[ 0.18281106  1.53737832 -1.63484956]
 [ 0.34358442 -1.43538547  0.47052418]]


In [63]:
# 10 random integers between 1 (inclusive) to 11 (exclusive)

np.random.randint(1, 11, 10)

array([2, 8, 5, 8, 1, 2, 2, 7, 5, 7], dtype=int32)

In [67]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(4,4))

array([[43, 44,  0,  4],
       [ 6, 48, 26, 23],
       [46,  1, 49, 30],
       [43, 12, 45, 39]], dtype=int32)